/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
namespace Vns.QuanLyDoanRa.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	//,IInfoService
	public class InfoService:GenericService<Info,Guid>, IInfoService
	{
	     public IInfoDao InfoDao
        {
            get { return (IInfoDao)Dao; }
            set { Dao = value; }
        }
	}
}
