/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
namespace Vns.QuanLyDoanRa.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	//,IVnsDmMucTieuMucService
	public class VnsDmMucTieuMucService:GenericService<VnsDmMucTieuMuc,Guid>, IVnsDmMucTieuMucService
	{
	     public IVnsDmMucTieuMucDao VnsDmMucTieuMucDao
        {
            get { return (IVnsDmMucTieuMucDao)Dao; }
            set { Dao = value; }
        }
	}
}
