/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
namespace Vns.QuanLyDoanRa.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	//,IVnsDmQuocGiaService
	public class VnsDmQuocGiaService:GenericService<VnsDmQuocGia,Guid>, IVnsDmQuocGiaService
	{
	     public IVnsDmQuocGiaDao VnsDmQuocGiaDao
        {
            get { return (IVnsDmQuocGiaDao)Dao; }
            set { Dao = value; }
        }
	}
}
