/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	//,IVnsDanhMucChucVuService
	public class VnsDanhMucChucVuService:GenericService<VnsDanhMucChucVu,Guid>, IVnsDanhMucChucVuService
	{
	     public IVnsDanhMucChucVuDao VnsDanhMucChucVuDao
        {
            get { return (IVnsDanhMucChucVuDao)Dao; }
            set { Dao = value; }
        }

         public IList<VnsDanhMucChucVu> GetAll()
         {
             IList<VnsDanhMucChucVu> lst = Dao.GetAll();
             List<VnsDanhMucChucVu> r = new List<VnsDanhMucChucVu>(lst);
             r.Sort(VnsDanhMucChucVu.CompareTenChucVu);
             return r;
         }
	}
}
