using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
using Spring.Transaction.Interceptor;
namespace Vns.QuanLyDoanRa.Service
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    //,IVnsDoanCongTacService
    public class VnsDoanCongTacService : GenericService<VnsDoanCongTac, Guid>, IVnsDoanCongTacService
    {
        public IVnsGiaoDichDao VnsGiaoDichDao;
        public IVnsChungTuDao VnsChungTuDao;
        public IVnsDuToanDoanDao VnsDuToanDoanDao;
        public IVnsQuyetToanDoanDao VnsQuyetToanDoanDao;
        public IVnsLichCongTacDao VnsLichCongTacDao;
        public IVnsThanhVienDao VnsThanhVienDao;

        public IVnsDoanCongTacDao VnsDoanCongTacDao
        {
            get { return (IVnsDoanCongTacDao)Dao; }
            set { Dao = value; }
        }
        public IList<VnsDoanCongTac> ListDoanCongTacTuNgayDenNgay(DateTime dTuNgay, DateTime dDenNgay)
        {
            return VnsDoanCongTacDao.ListDoanCongTacTuNgayDenNgay(dTuNgay, dDenNgay);
        }
        public IList<VnsDoanCongTac> GetByTrangThai(int p_trangthai)
        {
            return VnsDoanCongTacDao.GetByTrangThai(p_trangthai);
        }
        public IList<VnsDoanCongTac> GetByLoaiDoanRa(Guid LoaiDoanRaId)
        {
            return VnsDoanCongTacDao.GetByLoaiDoanRa(LoaiDoanRaId);
        }
        [Transaction]
        public void DeleteDoanCongTac(VnsDoanCongTac objDoanCongTac)
        {
            //Xoa chung tu
            if (objDoanCongTac.ChungTuId != new Guid())
            {
                VnsGiaoDichDao.DeleteByChungTu(objDoanCongTac.ChungTuId);
                VnsChungTuDao.DeleteById(objDoanCongTac.ChungTuId);
            }

            if (objDoanCongTac.DanhSachQuyetToanDoan != null)
            {
                Guid ChungTuId = new Guid();
                foreach (VnsQuyetToanDoan tmp in objDoanCongTac.DanhSachQuyetToanDoan)
                {
                    ChungTuId = tmp.ChungTuId;
                }
                if (ChungTuId != new Guid())
                {
                    VnsGiaoDichDao.DeleteByChungTu(ChungTuId);
                    VnsChungTuDao.DeleteById(ChungTuId);
                }
            }

            VnsDuToanDoanDao.DeleteByDoanCongTac(objDoanCongTac.Id, -1);
            VnsQuyetToanDoanDao.DeleteByDoanCtId(objDoanCongTac.Id);
            VnsLichCongTacDao.DeleteByDoanCongTac(objDoanCongTac.Id);
            VnsThanhVienDao.DeleteByDoanCongTac(objDoanCongTac.Id);
            VnsDoanCongTacDao.DeleteById(objDoanCongTac.Id);
        }

        public void SaveDoanCongTac(ref VnsDoanCongTac objDoanCongTac)
        {
            VnsDoanCongTacDao.Merge(objDoanCongTac);
        }


        public IList<VnsDoanCongTac> GetAllOrderByNgayDi()
        {
            return VnsDoanCongTacDao.GetAllOrderByNgayDi();
        }

        #region Them truong hop bo sung
        public IList<VnsDoanCongTac> GetDoanRa(int Nam)
        {
            return VnsDoanCongTacDao.GetDoanRa(Nam);
        }

        public IList<VnsDoanCongTac> GetDoanRaPhu(int Nam)
        {
            return VnsDoanCongTacDao.GetDoanRaPhu(Nam);
        }

        public IList<VnsDoanCongTac> GetDoanRaByDoanRaBanDau(Guid DoanRaId)
        {
            return VnsDoanCongTacDao.GetDoanRaByDoanRaBanDau(DoanRaId);
        }

        public IList<VnsDoanCongTac> GetDoanRaTongHopQT(int Nam)
        {
            List<VnsDoanCongTac> lst = new List<VnsDoanCongTac>( VnsDoanCongTacDao.GetDoanRaPhu(Nam));
            lst.Sort(VnsDoanCongTac.CompareIdBanDau);

            IList<VnsDoanCongTac> tmplst = new List<VnsDoanCongTac>();
            Guid tmpId = new Guid();
            VnsDoanCongTac tmpdct = new VnsDoanCongTac();
            foreach (VnsDoanCongTac tmp in lst)
            {
                if (tmpId != tmp.IdBanDau)
                {
                    tmpdct = new VnsDoanCongTac();
                    tmpdct = tmp;
                    tmpdct.TbQuyetToanExt = tmp.SoThongBaoQuyetToan;
                    tmpId = tmp.IdBanDau;
                    tmplst.Add(tmpdct);
                }
                else
                {
                    tmpdct.TbQuyetToanExt += "; " + tmp.SoThongBaoQuyetToan;
                }
            }

            return tmplst;
        }
        #endregion
    }
}
