/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
using Vns.Erp.Core.Domain;
namespace Vns.QuanLyDoanRa.Service
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    //,IVnsDmHeThongService
    public class VnsDmHeThongService : GenericService<VnsDmHeThong, Guid>, IVnsDmHeThongService
    {
        public IVnsDmHeThongDao VnsDmHeThongDao
        {
            get { return (IVnsDmHeThongDao)Dao; }
            set { Dao = value; }
        }

        public IList<VnsDmHeThong> GetByDoiTuong(String DoiTuong)
        {
            return VnsDmHeThongDao.GetByDoiTuong(DoiTuong);
        }

        public IList<VnsDmHeThong> GetByDoiTuongAndMa(String DoiTuong, String Ma)
        {

            return VnsDmHeThongDao.GetByDoiTuongAndMa(DoiTuong, Ma);
        }
    }
}
