/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Service
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    //,IVnsLichCongTacService
    public class VnsLichCongTacService : GenericService<VnsLichCongTac, Guid>, IVnsLichCongTacService
    {
        public IVnsLichCongTacDao VnsLichCongTacDao
        {
            get { return (IVnsLichCongTacDao)Dao; }
            set { Dao = value; }
        }
        public IList<VnsLichCongTac> GetByDoanCongTacAndNhomNuoc(Guid CongTacId, int LoaiQuocGia)
        {
            return VnsLichCongTacDao.GetByDoanCongTacAndNhomNuoc(CongTacId, LoaiQuocGia);
        }
        public IList<VnsLichCongTac> GetByDoanCongTac(Guid CongTacId)
        {
            return VnsLichCongTacDao.GetByDoanCongTac(CongTacId);
        }

        public Boolean DeleteByDoanCongTac(Guid CongTacId)
        {
            return VnsLichCongTacDao.DeleteByDoanCongTac(CongTacId);
        }
    }
}
