/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Service
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	//,IVnsNghiepVuService
	public class VnsNghiepVuService:GenericService<VnsNghiepVu,Guid>, IVnsNghiepVuService
	{
	     public IVnsNghiepVuDao VnsNghiepVuDao
        {
            get { return (IVnsNghiepVuDao)Dao; }
            set { Dao = value; }
        }

         public IList<VnsNghiepVu> GetDatasourceByLoaiCt(IList<VnsNghiepVu> lstNghiepVu,VnsLoaiChungTu objLoaiChungTu)
         {
             IList<VnsNghiepVu> lstReturn = new List<VnsNghiepVu>();
             IList<String> lstMaCt = new List<String>();

             if (objLoaiChungTu.LoaiPhieu == 1)
             {
                 lstMaCt = objLoaiChungTu.MaTkNo.Split(';');
             }
             else
             {
                 lstMaCt = objLoaiChungTu.MaTkCo.Split(';');
             }

             foreach (VnsNghiepVu objNv in lstNghiepVu)
             {
                 foreach (String str in lstMaCt)
                 {
                     if (objNv.MaNghiepVu == str)
                     {
                         lstReturn.Add(objNv);
                     }
                 }
             }

             return lstReturn;
         }

         public IList<VnsNghiepVu> GetNghiepVuKtk(IList<VnsNghiepVu> lstNghiepVu, bool Flag, VnsLoaiChungTu objLoaiChungTu)
         {
             IList<VnsNghiepVu> lstReturn = new List<VnsNghiepVu>();
             IList<String> lstMaCt = new List<String>();

             if (Flag)
             {
                 lstMaCt = objLoaiChungTu.MaTkCo.Split(';');
                 
             }
             else
             {
                 lstMaCt = objLoaiChungTu.MaTkNo.Split(';');
             }

             foreach (VnsNghiepVu objNv in lstNghiepVu)
             {
                 foreach (String str in lstMaCt)
                 {
                     if (objNv.MaNghiepVu == str)
                     {
                         lstReturn.Add(objNv);
                     }
                 }
             }

             return lstReturn;
         }

	}
}
