/*
insert license info here
*/
using System.Collections;
using System.ComponentModel;
using System.Data;
using System;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.QuanLyDoanRa.Service.Interface;
using Vns.Erp.Core.Service;
using Vns.Erp.Core.Service.Interface;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Service
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    //,IVnsThanhVienService
    public class VnsThanhVienService : GenericService<VnsThanhVien, Guid>, IVnsThanhVienService
    {
        public IVnsThanhVienDao VnsThanhVienDao
        {
            get { return (IVnsThanhVienDao)Dao; }
            set { Dao = value; }
        }

        public IList<VnsThanhVien> GetByDoanCongTac(Guid CongTacId)
        {
            return VnsThanhVienDao.GetByDoanCongTac(CongTacId);
        }

        public Boolean DeleteByDoanCongTac(Guid CongTacId)
        {
            return VnsThanhVienDao.DeleteByDoanCongTac(CongTacId);
        }

        public IList<VnsThanhVien> GetThanhVienByLichCongTacDoanRa(Guid LichCongTacId, Guid DoanRaId)
        {
            return VnsThanhVienDao.GetThanhVienByLichCongTacDoanRa(LichCongTacId, DoanRaId);
            //IList props = new ArrayList();
            //IList values = new ArrayList();
            //props.Add("LichCongTacId");
            //values.Add(LichCongTacId);

            //props.Add("CongTacId");
            //values.Add(DoanRaId);

            //return VnsThanhVienDao.List(-1, -1, props, values, null);
        }
        public IList<VnsThanhVien> GetThanhVienByLichCongTacDoanRa(Guid LichCongTacId, Guid DoanRaId, int LoaiThanhVien)
        {
            return VnsThanhVienDao.GetThanhVienByLichCongTacDoanRa(LichCongTacId, DoanRaId, LoaiThanhVien);
        }
    }
}
