/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.QuanLyDoanRa.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Dao
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	public interface IVnsLoaiChungTuDao:IDao<VnsLoaiChungTu,Guid>
	{
        VnsLoaiChungTu GetByMa(String MaLoaiChungTu);
        IList<VnsLoaiChungTu> GetByGroup(string MaDmCha);
	}
}
