/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.QuanLyDoanRa.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Dao
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    public interface IVnsThanhVienDao : IDao<VnsThanhVien, Guid>
    {
        IList<VnsThanhVien> GetByDoanCongTac(Guid CongTacId);
        IList<VnsThanhVien> GetThanhVienByLichCongTacDoanRa(Guid LichCongTacId, Guid DoanRaId);
        IList<VnsThanhVien> GetThanhVienByLichCongTacDoanRa(Guid LichCongTacId, Guid DoanRaId,int LoaiThanhVien);
        Boolean DeleteByDoanCongTac(Guid CongTacId);
    }
}
