/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.QuanLyDoanRa.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Dao
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    public interface IVnsGiaoDichDao : IDao<VnsGiaoDich, Guid>
    {
        IList<VnsGiaoDich> GetByChungTu(Guid ChungTuId);
        IList<VnsGiaoDich> GetByDoanRaCoId(Guid DoanRaCoId);
        IList<VnsGiaoDich> GetByDoanRaNoId(Guid DoanRaNoId);
        IList<VnsGiaoDich> GetByMaTKNo(String strMaTKNo);
        IList<VnsGiaoDich> GetByMaTKCo(string strMaTKCo);
        Boolean DeleteByChungTu(Guid ChungTuId);
        IList<VnsGiaoDich> GetTUByDoanRaId(Guid p_DoanRaId);

        IList<VnsGiaoDich> GetByDoanRa(Guid DoanRaid, String MaTkNo, String MaTkCo);
        IList<VnsGiaoDich> GetNhap4FIFO(DateTime TuNgay, DateTime DenNgay, Guid NguonId, String TkNo, String TkCo);
        IList<VnsGiaoDich> GetNhap4FIFO(DateTime TuNgay, DateTime DenNgay, Guid NguonId, String NghiepVu);
        IList<VnsGiaoDich> GetBy(DateTime TuNgay, DateTime DenNgay, Guid NguonId, String NghiepVu);
        
        IList<VnsGiaoDich> GetTUByDoanRaIdGroupByTyGia(Guid p_DoanRaId);
        IList<VnsGiaoDich> GetHUKoQTByDoanRaIdGroupByTyGia(Guid p_DoanRaId);
    }
}
