/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.QuanLyDoanRa.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
namespace Vns.QuanLyDoanRa.Dao
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	public interface IVnsDmMucTieuMucDao:IDao<VnsDmMucTieuMuc,Guid>
	{	

	}
}
