/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.QuanLyDoanRa.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Dao
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	public interface IVnsDoanCongTacDao:IDao<VnsDoanCongTac,Guid>
	{
        IList<VnsDoanCongTac> ListDoanCongTacTuNgayDenNgay(DateTime dTuNgay, DateTime dDenNgay);
        IList<VnsDoanCongTac> GetByTrangThai(int p_trangthai);
        IList<VnsDoanCongTac> GetByLoaiDoanRa(Guid LoaiDoanRaId);
        IList<VnsDoanCongTac> GetAllOrderByNgayDi();
        IList<VnsDoanCongTac> GetByNgayQT(decimal p_trangthai, DateTime p_TuNgay, DateTime p_DenNgay, Guid p_loaiDR);
        IList<VnsDoanCongTac> GetByNgayQTBoSung(decimal p_trangthai, DateTime p_TuNgay, DateTime p_DenNgay, Guid p_loaiDR);
        IList<VnsDoanCongTac> GetDoanRaPhu(int Nam);
        IList<VnsDoanCongTac> GetDoanRa(int Nam);
        IList<VnsDoanCongTac> GetDoanRaByDoanRaBanDau(Guid IdBanDau);
	}
}
