/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.QuanLyDoanRa.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
using System.Collections.Generic;
using Vns.QuanLyDoanRa.Domain.Report;
namespace Vns.QuanLyDoanRa.Dao
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>	
	public interface IVnsDuToanDoanDao:IDao<VnsDuToanDoan,Guid>
	{
        IList<VnsDuToanDoan> GetByDoanCongTac(Guid CongTacId);
        IList<VnsInQtTu> GetDataInDt(Guid CongTacId);
        List<BC03DR> ListChuaQuyetToan(DateTime p_TuNgay, DateTime p_DenNgay, Guid p_LoaiDoanRa);
        IList<VnsDuToanDoan> GetByDoanCongTac(Guid CongTacId, int LanDuToan);
        void DeleteByDoanCongTac(Guid CongTacId, int LanDuToan);
	}
}
