/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.QuanLyDoanRa.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
using System.Collections.Generic;
using Vns.QuanLyDoanRa.Domain.Report;
namespace Vns.QuanLyDoanRa.Dao
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    public interface IVnsQuyetToanDoanDao : IDao<VnsQuyetToanDoan, Guid>
    {
        IList<VnsQuyetToanDoan> GetByDoanCongTac(Guid CongTacId);
        IList<VnsQuyetToanDoan> GetByDoanCongTac(Guid CongTacId, Decimal LanQuyetToan);
        Boolean DeleteByDoanCtId(Guid CongTacId);
        IList<VnsInQtTu> GetDataInQt(Guid CongTacId);
        IList<VnsInQtTu> GetDataInQTbyDoanCtac(Guid CongTacId, Decimal LanQuyetToan);
    }
}
