/*
insert license info here
*/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using Vns.QuanLyDoanRa.Domain;
using Vns.Erp.Core.Dao;
using Vns.Erp.Core.Domain;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Dao
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>	
    public interface IVnsChungTuDao : IDao<VnsChungTu, Guid>
    {
        IList<VnsChungTu> LoadByChungTu(String MaLoaiChungTu);
        IList<VnsChungTu> ListChungTuDenNgay(DateTime dNgayChungTu);
        IList<VnsChungTu> ListChungTuTuNgayDenNgay(DateTime dTuNgay, DateTime dDenNgay, string strMaLoaiChungTu);
        IList<VnsChungTu> SearchChungTu(String p_MaLoaiCt, DateTime p_TuNgay, DateTime p_DenNgay, String p_MaTkNo, String p_MaTkCo, Guid p_DoanRaId, Guid p_LoaiDoanRaId, Decimal p_SoTienTu, Decimal p_SoTienDen, String p_NguoiTamUng, String p_NoiDung);
        Int32 GetRowCount(string p_maLoaiCt);
        void Delete_By_Id(Guid ChungTuId);
    }
}
