/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	public partial class VnsChungTu : DomainObject<Guid>
	{
        IList<VnsGiaoDich> _LstGiaoDich;
        [DataMember]
        public IList<VnsGiaoDich> LstGiaoDich
        {
            get { return _LstGiaoDich; }
            set { _LstGiaoDich = value; }
        }

        #region Extend Property
        public int DisplayMonth
        {
            get
            {
                return _ngayct.Month;
            }
        }

        public int DisplayYear
        {
            get
            {
                return _ngayct.Year;
            }
        }
        #endregion

        public VnsChungTu Clone()
        {
            return (VnsChungTu)this.MemberwiseClone();
        }
    }
}
