/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
using Vns.QuanLyDoanRa.Dao.NHibernate;
namespace Vns.QuanLyDoanRa.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	public partial class VnsDinhMuc : DomainObject<Guid>
	{   
        //private VnsDmQuocGia _Nuoc;
        //public Vns.QuanLyDoanRa.Domain.VnsDmQuocGia Nuoc
        //{
        //    get { return _Nuoc; }
        //    set { _Nuoc = value; }
        //}
 
        //public String TenNuoc
        //{
        //    get
        //    {
        //        if (_Nuoc != null)
        //        {
        //            return _Nuoc.TenNuoc;
        //        }
        //        return null;
        //    }
        //}
        private VnsDmMucTieuMuc _Muc;

        public VnsDmMucTieuMuc Muc
        {
            
            get { return _Muc; }
            set { _Muc = value; }
        }

        public String TenMuc
        {
            get
            {
                if (_Muc != null)
                {
                    return _Muc.TenMuc;
                }
                return null;
            }
        }
	}
}
