/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	public partial class VnsDmQuocGia : DomainObject<Guid>
	{
        //private IList<VnsDmHeThong> _HeThong;
        //public IList<VnsDmHeThong> HeThong
        //{
        //    get { return _HeThong; }
        //    set { _HeThong = value; }
        //}

        //public String DoiTuong
        //{
        //    get
        //    {
        //        if (_HeThong != null)
        //        {
        //            return _HeThong.DoiTuong;
        //        }
        //        return null;
        //    }
        //}
        //public IList<VnsDinhMuc> DinhMuc
        //{
        //    get { return _dinhMuc; }
        //    set { _dinhMuc = value; }
        //}
        
	}
}
