/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
namespace Vns.QuanLyDoanRa.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	
	[Serializable]
	[DataContract(Namespace ="http://Vns.QuanLyDoanRa",IsReference=true)]
	public partial class VnsDmHeThong : DomainObject<Guid>, INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }		
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private Guid _hethongid; 
		private string _ma; 
		private string _ten; 
		private string _doituong; 
		private int _giatri; 
		private int _thutu;
        private string _trangThaiPhieu;
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public VnsDmHeThong()
		{
				_hethongid =  new Guid(); 
				_ma =  String.Empty; 
				_ten =  String.Empty; 
				_doituong =  String.Empty; 
				_giatri = 0; 
				_thutu = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  Guid HeThongId
		{
			get { return _hethongid; }
			set { _isChanged |= (_hethongid != value); _hethongid = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string Ma
		{
			get { return _ma; }
			set	
			{
				if ( value != null)
					if( value.Length > 32)
						throw new ArgumentOutOfRangeException("Invalid value for Ma", value, value.ToString());
				
				_isChanged |= (_ma != value); _ma = value;
			}
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string Ten
		{
			get { return _ten; }
			set	
			{
				if ( value != null)
					if( value.Length > 128)
						throw new ArgumentOutOfRangeException("Invalid value for Ten", value, value.ToString());
				
				_isChanged |= (_ten != value); _ten = value;
			}
			}

        [DataMember]
        public string TrangThaiPhieu
        {
            get { return _trangThaiPhieu; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for _trangThaiPhieu", value, value.ToString());

                _isChanged |= (_trangThaiPhieu != value); _trangThaiPhieu = value;
            }
        }
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string DoiTuong
		{
			get { return _doituong; }
			set	
			{
				if ( value != null)
					if( value.Length > 32)
						throw new ArgumentOutOfRangeException("Invalid value for DoiTuong", value, value.ToString());
				
				_isChanged |= (_doituong != value); _doituong = value;
			}
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  int GiaTri
		{
			get { return _giatri; }
			set { _isChanged |= (_giatri != value); _giatri = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  int ThuTu
		{
			get { return _thutu; }
			set { _isChanged |= (_thutu != value); _thutu = value; }
			}
			
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		
		#endregion
		
		
		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			VnsDmHeThong castObj = (VnsDmHeThong)obj; 
			return ( castObj != null ) &&
				( this._hethongid == castObj.HeThongId);
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			
			int hash = 57; 
			hash = 27 * hash * _hethongid.GetHashCode();
			return hash; 
		}
		#endregion
		
	}
}
