/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
namespace Vns.QuanLyDoanRa.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	public partial class VnsGiaoDich : DomainObject<Guid>
	{
        #region Extend Property
        private VnsChungTu _objChungTu;
        [DataMember]
        public virtual VnsChungTu objChungTu
        {
            get { return _objChungTu; }
            set { _objChungTu = value; }
        }

        private VnsDoanCongTac _objDoanCongTac;
        [DataMember]
        public virtual VnsDoanCongTac objDoanRa
        {
            get { return _objDoanCongTac; }
            set { _objDoanCongTac = value; }
        }

        [DataMember]
        public virtual Decimal SoTienConLai { get; set; }
        #endregion

        #region property tam, dung chi de tinh toan, ko luu
        public decimal SoTien_USD_Xuat_Cl
        { get; set; }
        public decimal SoTien_USD_Nhap_Cl
        { get; set; }
        #endregion

        public VnsGiaoDich Clone()
        {
            return (VnsGiaoDich)this.MemberwiseClone();
        }
    }
}
