/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
namespace Vns.QuanLyDoanRa.Domain
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
    /// </summary>


    [Serializable]
    [DataContract(Namespace = "http://Vns.QuanLyDoanRa", IsReference = true)]
    public partial class VnsGiaoDich : DomainObject<Guid>, INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        #region Private Members
        private bool _isChanged;
        private bool _isDeleted;
        private Guid _giaodichid;
        private Guid _chungtuid;
        private Guid _TkNoId;
        private string _MaTkNo;
        private string _TenTkNo;
        private Guid _TkCoId;
        private string _MaTkCo;
        private string _TenTkCo;
        private decimal _sotien;
        private decimal _tygia;
        private decimal _sotiennt;
        private Guid _KhachHangNoId;
        private Guid _KhachHangCoId;
        private Guid _DoanRaNoId;
        private Guid _DoanRaCoId;
        private Guid _LoaiDoanRaNoId;
        private Guid _LoaiDoanRaCoId;
        private Guid _MucTieuMucNoId;
        private Guid _MucTieuMucCoId;
        private string _NoiDung;
        private string _DienGiai;
        private string _MoTa;
        private decimal _TyGiaTuDong;
        private decimal _DuLuong;
        private Guid _NgoaiTeId;

       
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public VnsGiaoDich()
        {
            _giaodichid = new Guid();
            _chungtuid = new Guid();
            _TkNoId = new Guid();
            _MaTkNo = String.Empty;
            _TenTkNo = String.Empty;
            _TkCoId = new Guid();
            _MaTkCo = String.Empty;
            _TenTkCo = String.Empty;
            _sotien = 0;
            _tygia = 0;
            _sotiennt = 0;
            _KhachHangNoId = new Guid();
            _KhachHangCoId = new Guid();
            _DoanRaNoId = new Guid();
            _DoanRaCoId = new Guid();
            _LoaiDoanRaNoId = new Guid();
            _LoaiDoanRaCoId = new Guid();
            _MucTieuMucCoId = new Guid();
            _MucTieuMucNoId = new Guid();
            _NoiDung = String.Empty;
            _TyGiaTuDong = 0;
            _DienGiai = String.Empty;
            _MoTa = String.Empty;

        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid GiaoDichId
        {
            get { return _giaodichid; }
            set { _isChanged |= (_giaodichid != value); _giaodichid = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public Guid ChungTuId
        {
            get { return _chungtuid; }
            set { _isChanged |= (_chungtuid != value); _chungtuid = value; }
        }


        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid TkNoId
        {
            get { return _TkNoId; }
            set { _isChanged |= (_TkNoId != value); _TkNoId = value; }
        }


        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public string MaTkNo
        {
            get { return _MaTkNo; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaNghiepVu", value, value.ToString());

                _isChanged |= (_MaTkNo != value); _MaTkNo = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public string TenTkNo
        {
            get { return _TenTkNo; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenNghiepVu", value, value.ToString());

                _isChanged |= (_TenTkNo != value); _TenTkNo = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid TkCoId
        {
            get { return _TkCoId; }
            set { _isChanged |= (_TkCoId != value); _TkCoId = value; }
        }


        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public string MaTkCo
        {
            get { return _MaTkCo; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaNghiepVu", value, value.ToString());

                _isChanged |= (_MaTkCo != value); _MaTkCo = value;
            }
        }


        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public string TenTkCo
        {
            get { return _TenTkCo; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenNghiepVu", value, value.ToString());

                _isChanged |= (_TenTkCo != value); _TenTkCo = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		

        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTien
        {
            get { return _sotien; }
            set { _isChanged |= (_sotien != value); _sotien = value; }
        }

        [DataMember]
        public decimal TyGiaTuDong
        {
            get { return _TyGiaTuDong; }
            set { _isChanged |= (_TyGiaTuDong != value); _TyGiaTuDong = value; }
        }

        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal TyGia
        {
            get { return _tygia; }
            set { _isChanged |= (_tygia != value); _tygia = value; }
        }


        /// <summary>
        /// 
        /// </summary>		

        [DataMember]
        public decimal SoTienNt
        {
            get { return _sotiennt; }
            set { _isChanged |= (_sotiennt != value); _sotiennt = value; }
        }


        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid KhachHangNoId
        {
            get { return _KhachHangNoId; }
            set { _isChanged |= (_KhachHangNoId != value); _KhachHangNoId = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid KhachHangCoId
        {
            get { return _KhachHangCoId; }
            set { _isChanged |= (_KhachHangCoId != value); _KhachHangCoId = value; }
        }


        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid DoanRaNoId
        {
            get { return _DoanRaNoId; }
            set { _isChanged |= (_DoanRaNoId != value); _DoanRaNoId = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid DoanRaCoId
        {
            get { return _DoanRaCoId; }
            set { _isChanged |= (_DoanRaCoId != value); _DoanRaCoId = value; }
        }


        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid LoaiDoanRaNoId
        {
            get { return _LoaiDoanRaNoId; }
            set { _isChanged |= (_LoaiDoanRaNoId != value); _LoaiDoanRaNoId = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid LoaiDoanRaCoId
        {
            get { return _LoaiDoanRaCoId; }
            set { _isChanged |= (_LoaiDoanRaCoId != value); _LoaiDoanRaCoId = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid MucTieuMucNoId
        {
            get { return _MucTieuMucNoId; }
            set { _isChanged |= (_MucTieuMucNoId != value); _MucTieuMucNoId = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public Guid MucTieuMucCoId
        {
            get { return _MucTieuMucCoId; }
            set { _isChanged |= (_MucTieuMucCoId != value); _MucTieuMucCoId = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public string NoiDung
        {
            get { return _NoiDung; }
            set { _isChanged |= (_NoiDung != value); _NoiDung = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public string DienGiai
        {
            get { return _DienGiai; }
            set { _isChanged |= (_DienGiai != value); _DienGiai = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        [DataMember]
        public string MoTa
        {
            get { return _MoTa; }
            set { _isChanged |= (_MoTa != value); _MoTa = value; }
        }

        [DataMember]
        public decimal DuLuong
        {
            get { return _DuLuong; }
            set { _isChanged |= (_DuLuong != value); _DuLuong = value; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return _isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return _isDeleted; }
        }

        public Guid NgoaiTeId
        {
            get { return _NgoaiTeId; }
            set { _NgoaiTeId = value; }
        }

        #endregion


        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            _isDeleted = true;
            _isChanged = true;
        }


        #endregion


        #region Equals And HashCode Overrides
        /// <summary>
        /// local implementation of Equals based on unique value members
        /// </summary>
        public override bool Equals(object obj)
        {
            if (this == obj) return true;
            if ((obj == null) || (obj.GetType() != this.GetType())) return false;
            VnsGiaoDich castObj = (VnsGiaoDich)obj;
            return (castObj != null) &&
                (this._giaodichid == castObj.GiaoDichId);
        }

        /// <summary>
        /// local implementation of GetHashCode based on unique value members
        /// </summary>
        public override int GetHashCode()
        {

            int hash = 57;
            hash = 27 * hash * _giaodichid.GetHashCode();
            return hash;
        }
        #endregion

    }
}
