/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
namespace Vns.QuanLyDoanRa.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	public partial class VnsLichCongTac : DomainObject<Guid>
	{
        //private VnsDmQuocGia _NuocDen;

        //public VnsDmQuocGia NuocDen
        //{
        //    get { return _NuocDen; }
        //    set { _NuocDen = value; }
        //}

        //public String TenNuocDen
        //{
        //    get
        //    {
        //        if (_NuocDen != null)
        //        {
        //            return _NuocDen.TenNuoc;
        //        }
        //        return null;
        //    }
        //}

        //private VnsDmHeThong _TenTrangThai;

        //public VnsDmHeThong TenTrangThai
        //{
        //    get { return _TenTrangThai; }
        //    set { _TenTrangThai = value; }
        //}

        //public String Ten_TrangThai
        //{
        //    get
        //    {
        //        if (_TenTrangThai != null)
        //        {
        //            return _TenTrangThai.Ten;
        //        }
        //        return null;
        //    }
        //}

        private VnsDmQuocGia _objNuocDen;
        [DataMember]
        public virtual VnsDmQuocGia objNuocDen
        {
            get { return _objNuocDen; }
            set { _objNuocDen = value; }
        }
	}
}
