/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
namespace Vns.QuanLyDoanRa.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	
	[Serializable]
	[DataContract(Namespace ="http://Vns.QuanLyDoanRa",IsReference=true)]
	public partial class VnsQuyetToanDoan : DomainObject<Guid>, INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }		
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private Guid _quyettoanid; 
		private Guid _lichcongtacid; 
		private Guid _congtacid; 
		private Guid _mucid; 
		private string _tenkhoanchi; 
		private decimal _sotien; 
		private string _diengiai; 
		private DateTime _ngayct; 
		private DateTime _ngayht;
        private Guid _TkId;
        private string _MaTk;
        private string _TenTk;
        private decimal _TyGia;
        private decimal _SoTienVND;
        private decimal _LanQuyetToan;
        private Guid _chungTuId;
        private Guid _NgoaiTeId;

        
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public VnsQuyetToanDoan()
		{
				_quyettoanid =  new Guid(); 
				_lichcongtacid =  new Guid(); 
				_congtacid =  new Guid(); 
				_mucid =  new Guid(); 
				_tenkhoanchi =  String.Empty; 
				_sotien = 0; 
				_diengiai =  String.Empty; 
				_ngayct = DateTime.MaxValue; 
				_ngayht = DateTime.MaxValue;
                _TkId = new Guid();
                _MaTk = String.Empty;
                _TenTk = String.Empty;
                _TyGia = 0;
                _SoTienVND = 0;
                _LanQuyetToan = 0;
                _chungTuId = new Guid();
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  Guid QuyetToanId
		{
			get { return _quyettoanid; }
			set { _isChanged |= (_quyettoanid != value); _quyettoanid = value; }
			}

        [DataMember]
        public Guid ChungTuId
        {
            get { return _chungTuId; }
            set { _isChanged |= (_chungTuId != value); _chungTuId = value; }
        }
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  Guid LichCongTacId
		{
			get { return _lichcongtacid; }
			set { _isChanged |= (_lichcongtacid != value); _lichcongtacid = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  Guid CongTacId
		{
			get { return _congtacid; }
			set { _isChanged |= (_congtacid != value); _congtacid = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  Guid MucId
		{
			get { return _mucid; }
			set { _isChanged |= (_mucid != value); _mucid = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string TenKhoanChi
		{
			get { return _tenkhoanchi; }
			set	
			{
				if ( value != null)
					if( value.Length > 512)
						throw new ArgumentOutOfRangeException("Invalid value for TenKhoanChi", value, value.ToString());
				
				_isChanged |= (_tenkhoanchi != value); _tenkhoanchi = value;
			}
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  decimal SoTien
		{
			get { return _sotien; }
			set { _isChanged |= (_sotien != value); _sotien = value; }
			}

        [DataMember]
        public decimal TyGia
        {
            get { return _TyGia; }
            set { _isChanged |= (_TyGia != value); _TyGia = value; }
        }

        [DataMember]
        public decimal SoTienVND
        {
            get { return _SoTienVND; }
            set { _isChanged |= (_SoTienVND != value); _SoTienVND = value; }
        }
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  string DienGiai
		{
			get { return _diengiai; }
			set	
			{
				if ( value != null)
					if( value.Length > 512)
						throw new ArgumentOutOfRangeException("Invalid value for DienGiai", value, value.ToString());
				
				_isChanged |= (_diengiai != value); _diengiai = value;
			}
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  DateTime NgayCt
		{
			get { return _ngayct; }
			set { _isChanged |= (_ngayct != value); _ngayct = value; }
			}
			
			
		/// <summary>
		/// 
		/// </summary>		
		
		[DataMember]
		public  DateTime NgayHt
		{
			get { return _ngayht; }
			set { _isChanged |= (_ngayht != value); _ngayht = value; }
			}


        [DataMember]
        public Guid TkId
        {
            get { return _TkId; }
            set { _isChanged |= (_TkId != value); _TkId = value; }
        }

        [DataMember]
        public string MaTk
        {
            get { return _MaTk; }
            set
            {
                if (value != null)
                    if (value.Length > 32)
                        throw new ArgumentOutOfRangeException("Invalid value for MaTk", value, value.ToString());

                _isChanged |= (_MaTk != value); _MaTk = value;
            }
        }

        [DataMember]
        public string TenTk
        {
            get { return _TenTk; }
            set
            {
                if (value != null)
                    if (value.Length > 128)
                        throw new ArgumentOutOfRangeException("Invalid value for TenTk", value, value.ToString());

                _isChanged |= (_TenTk != value); _TenTk = value;
            }
        }

        [DataMember]
        public decimal LanQuyetToan
        {
            get { return Decimal.Round(_LanQuyetToan, 0); }
            set { _isChanged |= (_LanQuyetToan != value); _LanQuyetToan = value; }
        }

        /// <summary>
        /// 
        /// </summary>	
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}

        public Guid NgoaiTeId
        {
            get { return _NgoaiTeId; }
            set { _NgoaiTeId = value; }
        }
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		
		#endregion
		
		
		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			VnsQuyetToanDoan castObj = (VnsQuyetToanDoan)obj; 
			return ( castObj != null ) &&
				( this._quyettoanid == castObj.QuyetToanId);
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			
			int hash = 57; 
			hash = 27 * hash * _quyettoanid.GetHashCode();
			return hash; 
		}
		#endregion
		
	}
}
