/*
insert license info here
*/
using System;
using System.ComponentModel;
using Vns.Erp.Core.Domain;
using System.Runtime.Serialization;
using Vns.QuanLyDoanRa.Domain.Report;
using System.Collections.Generic;
namespace Vns.QuanLyDoanRa.Domain
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo And Modified By Hoang Quoc Dung
	/// </summary>

	public partial class VnsQuyetToanDoan : DomainObject<Guid>
	{
        #region Extend Property
        private VnsDmMucTieuMuc _objMucTieuMuc;
        [DataMember]
        public virtual VnsDmMucTieuMuc objMucTieuMuc
        {
            get { return _objMucTieuMuc; }
            set { _objMucTieuMuc = value; }
        }

        public virtual String HienThiLanQt
        {
            get
            {
                if (_LanQuyetToan == 0) return "Quyết toán lần đầu";
                else
                    return String.Format("Quyết toán lần thứ {0}", Decimal.Round(_LanQuyetToan, 0));
            }
        }
        #endregion
	}
}
