/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
using NHibernate.Criterion;
namespace Vns.QuanLyDoanRa.Dao.NHibernate
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
    /// </summary>
    //[Serializable]
    public sealed class VnsDinhMucDao : GenericDao<VnsDinhMuc, Guid>, IVnsDinhMucDao
    {
        public IList<VnsDinhMuc> GetByNgayApDung(DateTime NgayApDung, Decimal DinhMuc, bool flag)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<VnsDinhMuc>();
            isearch.Add(Restrictions.Le("NgayApDung", NgayApDung));
            //if (flag)
            //{
            //    isearch.Add(Restrictions.Eq("DinhMuc", DinhMuc));
            //}
            //else
            //{
            //    isearch.Add(Restrictions.Gt("DinhMuc",DinhMuc));
            //}
            isearch.AddOrder(Order.Asc("ThuTu"));
            return isearch.List<VnsDinhMuc>();
        }
    }
}
