/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
namespace Vns.QuanLyDoanRa.Dao.NHibernate
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>
	//[Serializable]
	public sealed class VnsDmHeThongDao:GenericDao<VnsDmHeThong,Guid>,IVnsDmHeThongDao
	{
        public IList<VnsDmHeThong> GetByDoiTuong(String DoiTuong)
        {
            String sql = "from VnsDmHeThong ht where ht.DoiTuong =:DoiTuong " +
                         " Order by ThuTu ASC";
            IQuery q = Session.CreateQuery(sql);
            q.SetParameter("DoiTuong", DoiTuong);
            return q.List<VnsDmHeThong>();
        }

        public IList<VnsDmHeThong> GetByDoiTuongAndMa(String DoiTuong, String Ma)
        {
            String sql = "from VnsDmHeThong ht where ht.DoiTuong =:DoiTuong and Ma =:Ma " +
                         " Order by ThuTu ASC";
            IQuery q = Session.CreateQuery(sql);
            q.SetParameter("DoiTuong", DoiTuong);
            q.SetParameter("Ma", Ma);
            return q.List<VnsDmHeThong>();
        }
	}
}
