/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
namespace Vns.QuanLyDoanRa.Dao.NHibernate
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>
	//[Serializable]
	public sealed class VnsDoanCongTacDao:GenericDao<VnsDoanCongTac,Guid>,IVnsDoanCongTacDao
	{
        public IList<VnsDoanCongTac> ListDoanCongTacTuNgayDenNgay(DateTime dTuNgay, DateTime dDenNgay)
        {
            String sql = "from VnsDoanCongTac ct where ct.NgayDi>=:dTuNgay and ct.NgayDi<=:dDenNgay";
            IQuery q = Session.CreateQuery(sql);
            q.SetParameter("dTuNgay", dTuNgay);
            q.SetParameter("dDenNgay", dDenNgay);
            return q.List<VnsDoanCongTac>();
        }

        public IList<VnsDoanCongTac> GetByTrangThai(int p_trangthai)
        {
            String sql = "from VnsDoanCongTac ct where ct.TrangThai=:p_trangthai";
            IQuery q = Session.CreateQuery(sql);
            q.SetParameter("p_trangthai", p_trangthai);
            return q.List<VnsDoanCongTac>();
        }

        public IList<VnsDoanCongTac> GetByLoaiDoanRa(Guid p_LoaiDoanRaId)
        {
            String sql = "from VnsDoanCongTac ct";
            
            if (p_LoaiDoanRaId != new Guid())
            {
                sql += " where ct.LoaiDoanRaId=:p_LoaiDoanRaId";                
            }

            IQuery q = Session.CreateQuery(sql);
            if (p_LoaiDoanRaId != new Guid())
            {
                q.SetParameter("p_LoaiDoanRaId", p_LoaiDoanRaId);
            }
            return q.List<VnsDoanCongTac>();
        }

        public IList<VnsDoanCongTac> GetAllOrderByNgayDi()
        {
            String sql = "from VnsDoanCongTac ct order by ct.NgayDi DESC";
            IQuery q = Session.CreateQuery(sql);
            return q.List<VnsDoanCongTac>();
        }

        public IList<VnsDoanCongTac> GetByNgayQT(decimal p_trangthai, DateTime p_TuNgay, DateTime p_DenNgay, Guid p_loaiDR)
        {
            String sql = "from VnsDoanCongTac ct " + 
                "where 1 = 1 " +
                (p_trangthai == 0 ? "" : "AND ct.TrangThai =: p_trangthai ") +
                (p_trangthai == 0 ? "" : "AND ct.NgayQuyetToan >=:p_TuNgay ") +
                (p_trangthai == 0 ? "" : "AND ct.NgayQuyetToan <=:p_DenNgay ") +
                ((p_loaiDR == new Guid()) ? "" : "AND ct.LoaiDoanRaId =: p_loaiDR ");
            IQuery q = Session.CreateQuery(sql);
            if(p_trangthai!=0) q.SetParameter("p_trangthai", p_trangthai);
            if (p_trangthai != 0) q.SetParameter("p_TuNgay", VnsConvert.CStartOfDate(p_TuNgay));
            if (p_trangthai != 0) q.SetParameter("p_DenNgay", VnsConvert.CEndOfDate(p_DenNgay));
            if (!(p_loaiDR == new Guid())) q.SetParameter("p_loaiDR", p_loaiDR);
            return q.List<VnsDoanCongTac>();
        }

        public IList<VnsDoanCongTac> GetByNgayQTBoSung(decimal p_trangthai, DateTime p_TuNgay, DateTime p_DenNgay, Guid p_loaiDR)
        {
            String sql = "select ct from VnsDoanCongTac ct " +
                "Inner join ct.DanhSachQuyetToanDoan qt " + 
                "Where 1 = 1 " + 
                           (p_trangthai == 0 ? "" : " AND ct.TrangThai =: p_trangthai ") +
                           ((p_loaiDR == new Guid()) ? "" : " AND ct.LoaiDoanRaId =: p_loaiDR ") +
                           ((p_trangthai == 0) ? "" : " AND qt.NgayCt >= :p_TuNgay And qt.NgayCt <= :p_DenNgay ") +
                           " AND qt.LanQuyetToan > 0 ";
            IQuery q = Session.CreateQuery(sql);
            if (p_trangthai != 0) q.SetParameter("p_trangthai", p_trangthai);
            if (p_trangthai != 0) q.SetParameter("p_TuNgay", VnsConvert.CStartOfDate(p_TuNgay));
            if (p_trangthai != 0) q.SetParameter("p_DenNgay", VnsConvert.CEndOfDate(p_DenNgay));
            if (!(p_loaiDR == new Guid())) q.SetParameter("p_loaiDR", p_loaiDR);
            return q.List<VnsDoanCongTac>();
        }

        #region Them truong hop bo sung
        public IList<VnsDoanCongTac> GetDoanRa(int Nam)
        {
            String sql = "from VnsDoanCongTac ct where ct.Id = ct.IdBanDau order by NgayQuyetToan desc";
            IQuery q = Session.CreateQuery(sql);
            
            return q.List<VnsDoanCongTac>();
        }

        public IList<VnsDoanCongTac> GetDoanRaPhu(int Nam)
        {
            String sql = "from VnsDoanCongTac ct order by ct.IdBanDau asc";
            IQuery q = Session.CreateQuery(sql);

            return q.List<VnsDoanCongTac>();
        }
       

        public IList<VnsDoanCongTac> GetDoanRaByDoanRaBanDau(Guid IdBanDau)
        {
            String sql = "from VnsDoanCongTac ct where ct.IdBanDau = :IdBanDau ";
            IQuery q = Session.CreateQuery(sql);

            q.SetParameter("IdBanDau", IdBanDau);

            return q.List<VnsDoanCongTac>();
        }
        #endregion
    }
}
