/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
using NHibernate.Criterion;
using NHibernate.Transform;
namespace Vns.QuanLyDoanRa.Dao.NHibernate
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>
	//[Serializable]
	public sealed class VnsLichCongTacDao:GenericDao<VnsLichCongTac,Guid>,IVnsLichCongTacDao
	{
        public IList<VnsLichCongTac> GetByDoanCongTac(Guid CongTacId)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<VnsLichCongTac>();
            isearch.Add(Restrictions.Eq("CongTacId", CongTacId));

            return isearch.List<VnsLichCongTac>();
        }

        public IList<VnsLichCongTac> GetByDoanCongTacAndNhomNuoc(Guid CongTacId, int LoaiQuocGia)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<VnsLichCongTac>();
            isearch.Add(Restrictions.Eq("CongTacId", CongTacId));
            isearch.Add(Restrictions.Eq("LoaiQuocGia", LoaiQuocGia));
            return isearch.List<VnsLichCongTac>();
        }

        public Boolean DeleteByDoanCongTac(Guid CongTacId)
        {
            string DeleteSQL = "Delete from VnsLichCongTac where CongTacId = :CongTacId";
            IQuery DeleteQuery = NHibernateSession.CreateQuery(DeleteSQL);
            DeleteQuery.SetParameter("CongTacId", CongTacId);

            int r = DeleteQuery.ExecuteUpdate();
            return r != 0;
        }

        public IList<VnsLichCongTac> GetNuocDen(Guid CongTacId)
        {
            String sql ="Select nd.TenNuoc as DiaDiem " +
                        "From VnsLichCongTac ct " +
                        "Inner join ct.objNuocDen nd " +
                        "Where ct.CongTacId=:CongTacId ";
            IQuery q = NHibernateSession.CreateQuery(sql);
            q.SetParameter("CongTacId", CongTacId);
            q.SetResultTransformer(Transformers.AliasToBean<VnsLichCongTac>());
            return q.List<VnsLichCongTac>();
                            
        }
	}
}
