/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
using NHibernate.Criterion;
namespace Vns.QuanLyDoanRa.Dao.NHibernate
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>
	//[Serializable]
	public sealed class VnsLoaiChungTuDao:GenericDao<VnsLoaiChungTu,Guid>,IVnsLoaiChungTuDao
	{
        public VnsLoaiChungTu GetByMa(String MaLoaiChungTu)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<VnsLoaiChungTu>();
            isearch.Add(Restrictions.Eq("MaLoaiChungTu", MaLoaiChungTu));

            IList<VnsLoaiChungTu> lst = isearch.List<VnsLoaiChungTu>();
            if (lst != null && lst.Count > 0)
                return lst[0];
            else
                return null;
        }

        public IList<VnsLoaiChungTu> GetByGroup(string MaDmCha)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<VnsLoaiChungTu>();
            isearch.Add(Restrictions.Eq("MaDmCha", MaDmCha));

            return isearch.List<VnsLoaiChungTu>();
        }
	}
}
