/*
insert license info here
*/
using System;
using NHibernate;
using NHibernate.Cfg;
using Nullables;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Collections.Generic;
using Vns.Erp.Core.Dao.NHibernate;
using Vns.QuanLyDoanRa.Domain;
using Vns.QuanLyDoanRa.Dao;
using Vns.Erp.Core.Dao;
using Spring.Transaction.Interceptor;
using NHibernate.Criterion;
namespace Vns.QuanLyDoanRa.Dao.NHibernate
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping adapted by Gustavo
	/// </summary>
	//[Serializable]
	public sealed class VnsThanhVienDao:GenericDao<VnsThanhVien,Guid>,IVnsThanhVienDao
	{
        public IList<VnsThanhVien> GetByDoanCongTac(Guid CongTacId)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<VnsThanhVien>();
            isearch.Add(Restrictions.Eq("CongTacId", CongTacId));

            return isearch.List<VnsThanhVien>();
        }

        public IList<VnsThanhVien> GetThanhVienByLichCongTacDoanRa(Guid LichCongTacId, Guid DoanRaId)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<VnsThanhVien>();
            isearch.Add(Restrictions.Eq("LichCongTacId", LichCongTacId));
            isearch.Add(Restrictions.Eq("CongTacId", DoanRaId));

            return isearch.List<VnsThanhVien>();
        }
        public IList<VnsThanhVien> GetThanhVienByLichCongTacDoanRa(Guid LichCongTacId, Guid DoanRaId, int LoaiThanhVien)
        {
            ICriteria isearch = NHibernateSession.CreateCriteria<VnsThanhVien>();
            isearch.Add(Restrictions.Eq("LichCongTacId", LichCongTacId));
            isearch.Add(Restrictions.Eq("CongTacId", DoanRaId));
            isearch.Add(Restrictions.Eq("PhanLoai", LoaiThanhVien));
            return isearch.List<VnsThanhVien>();
        }
        public Boolean DeleteByDoanCongTac(Guid CongTacId)
        {
            string DeleteSQL = "Delete from VnsThanhVien where CongTacId = :CongTacId";
            IQuery DeleteQuery = NHibernateSession.CreateQuery(DeleteSQL);
            DeleteQuery.SetParameter("CongTacId", CongTacId);

            int r = DeleteQuery.ExecuteUpdate();
            return r != 0;
        }
	}
}
